pollday/game/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('gameplay/', views.game_view, name='gameplay'),
    path('statistics/', views.game_statistics, name = 'statistics'),
]

pollday/pollday/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.debug import default_urlconf
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('django', default_urlconf),
    path('polls/', include('polls.urls')),
    path('marks/', include('marks.urls')),
    path('game/', include('game.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pollday/polls/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('startpage/', views.startpage, name='startpage'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.UserLogout.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='registration'),
    path('books/', views.book_view, name='books'),
    path('book/<int:pk>/', views.book_detail_view, name='book-detail'),
    path('start/', views.index, name='index'),
    path('time/', views.dtnow, name='dtnow'),
    path('welcomepage/', views.welcome_view ,name='welcome'),
]

pollday/polls/models.py
from django.db import models
from django.core.validators import RegexValidator

class Author(models.Model):
    first_name = models.CharField('Имя автора', validators=[
                            RegexValidator('^[А-ЯЁ][а-яё]+')],max_length=50)
    last_name = models.CharField('Фамилия автора', validators=[
                            RegexValidator('^[А-ЯЁ][а-яё]+')],max_length=50)
    date_of_birth = models.DateField('Дата рождения', null=True, blank=True)
    date_of_death = models.DateField('Дата смерти', validators=[
                                    RegexValidator('((0?[1-9])|([12]\d)|(3[01]))\.((0?[1-9])|(1[0-2]))\.(1[0-9]{3})|(20[01]\d)|(202[0-2])')
                                        ], null=True, blank=True)
    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

class Genre(models.Model):
     g_name = models.CharField('Жанр', max_length=50, help_text='Введите жанр книги')
     def __str__(self):
         return self.g_name

class Publisher(models.Model):
    pub_name = models.CharField('Издательство', max_length=50)
    def __str__(self):
        return self.pub_name


class Book(models.Model):
    class Meta:
        verbose_name = 'Книга'
        verbose_name_plural = 'Книги'
    title = models.CharField('Наименование книги',
                            max_length=50)
    genre = models.ManyToManyField(Genre, verbose_name='Жанр')
    author = models.ForeignKey(Author, verbose_name = 'Автор', on_delete=models.SET_NULL, null=True)
    pub_year = models.PositiveIntegerField('Год публикации', validators=[RegexValidator('(1[0-9]{3})|(20[01]\d)|(202[0-2])')])
    publisher = models.ForeignKey(Publisher, verbose_name = 'Издательство', on_delete=models.SET_NULL, null=True)
    image = models.ImageField(verbose_name='Обложка',upload_to = 'images/', null=True, blank=True)
    def __str__(self):
        return '"%s", %s' %(self.title, self.author)

class Year(models.Model):
    name = models.CharField('Имя', max_length=50)
    year = models.PositiveIntegerField('Год публикации', validators=[RegexValidator('(1[0-9]{3})|(20[01]\d)|(202[0-2])')])
    def __str__(self):
        return self.name

pollday/polls/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username', 'first_name', 'email', 'password1', 'password2']

pollday/polls/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.http import Http404
from datetime import datetime
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import SignUpForm
from .models import Book, Author, Genre

class SignUp(SuccessMessageMixin, CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'polls/registration.html'

class UserLogin(LoginView):
    template_name = 'polls/login.html'

class UserLogout(LogoutView):
    template_name = 'polls/logout.html'

# class BooksList(LoginRequiredMixin, ListView):
#     model = Book
#     template_name = 'polls/books.html'
@login_required
def book_detail_view(request,pk=1):
    try:
        book_id=Book.objects.get(pk=pk)
    except Book.DoesNotExist:
        raise Http404("Book does not exist")
    return render(
        request,
        'polls/book_detail.html',
        context={'book':book_id,}
    )

@login_required
def book_view(request):
    book = Book.objects.all()
    return render(request, 'polls/books.html', {"book":book})

@login_required
def welcome_view(request):
    return render(request, 'polls/userpage.html')

def index(request):
    return render(request, 'polls/index.html')

def dtnow(request):
    datenow = datetime.now()
    return render(request,'polls/dtnow.html', {'mydate': datenow})

def startpage(request):
    return render(request, 'polls/startpage.html')

pollday/polls/templates/polls/book_detail.html
{% extends "base.html" %}
{% block title %}Добавить название{% endblock %}
{% block content %}
<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->

<img class="bookspg" src="{{book.image.url}}" alt="img"> 

{% endblock %}

pollday/polls/templates/polls/books.html
{% extends "base.html" %}
{% block title %}Удача{% endblock %}
{% block content %}
<ul>
    {% for item in book %}
        <li> 
           <img class="bookspg" src="{{item.image.url}}" alt="img"> 
           <a href="">{{item.title}}</a>
        </li>
        
    {% endfor %}
    </ul>

    <!-- <ul>
        {% for item in author %}
            <li> 
                {{item.1}}
            </li>
        {% endfor %}
        </ul> -->
    <!-- {% if book_list %}
    <h1>Список книг</h1>
    <ul>
    {% for book in book_list %}
        <li> 
            {{book}}
        </li>
    {% endfor %}
    </ul>
    {%else%}
    <p>Нет книг &#9785; </p>
    {%endif%} -->
{% endblock %}

pollday/polls/templates/polls/dtnow.html
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8">
		<title>
			Время
		</title>
        {% load static %}

        
        <link rel="stylesheet" 
            type="text/css" 
            href="{% static 'style/style.css' %}">
        <link rel="stylesheet" 
            type="text/css" 
            href="{% static 'style/color.css' %}">
        <!-- <script
            src="{% static 'script/script.js' %}">
        </script> -->
	</head>
	<body class="dt">
        <p class="datetime">
            {{ mydate|date:'d-m-Y D H:i' }}
        </p>
	</body>
</html>

pollday/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8">
		<title>
			Вопросы
		</title>
        {% load static %}

        
        <link rel="stylesheet" 
            type="text/css" 
            href="{% static 'style/style.css' %}">
        <link rel="stylesheet" 
            type="text/css" 
            href="{% static 'style/color.css' %}">
        <script
            src="{% static 'script/script.js' %}">
        </script>
	</head>
	<body>
        <h1>Ответы на вопросы</h1>
        <ol>
            <li>
                Как создать проект? 
                    
            </li>
            <div>
                <input type="button" value="&raquo;" onclick="toopen(this)">
                <p class="qes"> Для создания проекта в папке с проектом надо развернуть виртуальную среду.
                    Есть разные способы, я использую pipenv: <br/>
                    Создаю папку Pipfile в папке проекта <br/>
                    Запускаю <span> pipenv shell</span> <br/>
                    если успешно, в консоле перед адресом папки будет указано:
                    (название проекта)/адрес проекта/ <br>
                    утсновить <span> django: pipenv install Django</span>
                </p>
            </div>
            </ul>
            <li>
                Как создать приложение?
                    
            </li> 
            <div>
                <input type="button" value="&raquo;" onclick="toopen(this)">
                <p class="qes">
                    <span> django-admin startproject наименование приложения</span>
                </p>
            </div>
            <li>
                Как запустить тестовый веб-сервер?
            </li>
            <div>   
                <input type="button" value="&raquo;" onclick="toopen(this)">
                <p class="qes">Запуск производится из папки с файлом manage.py. 
                Для переход использовать команду <span> cd название папки </span>
                Запуск на linux: <span> python3 manage.py runserver 
                (5000 пример запуска по заданному порту)</span>
                </p>
            </div> 
            <li>
                Как открыть на своем компьютере свой сайт на Джанго?
            </li>
            <div>
                <input type="button" value="&raquo;" onclick="toopen(this)">
                <p class="qes">В адресной строке можно ввести локальный ip адрес 127.0.0.1:порт <br>
                    Так же при запуске тестового веб-сервера можно пройти по ссылке,
                    которая будет указана в консоле
                </p>
            </div> 
            <li>
                Как узнать, что мы допустили ошибку при редактировании файлов проекта?
            </li>
            <div> 
                <input type="button" value="&raquo;" onclick="toopen(this)">   
                <p class="qes">Ошибка будет выведена в консоле, так же, возможно, 
                    тестовый сайт будет отображать ошибку 404
                </p>
            </div> 
            <li>
                Как вывести на страницу HTML-код?
            </li>
            <div>
                <input type="button" value="&raquo;" onclick="toopen(this)">    
                <p class="qes">HTML страница может быть расположена в папке "templates",
                    чтобы программа могла найти шаблон, для этого надо прописать в программе
                    какой шаблон ей надо использовать,
                    так же можно разместить код в файле views.py,
                    HttpResponse('html код')
                </p>
            </div>  
            <li>
                Почему команда запуска веб-сервера "ничего не пишет"?
            </li>
            <div>
                <input type="button" value="&raquo;" onclick="toopen(this)">       
                <p class="qes">
                    Она пишет: <br>
                    <span> Watching for file changes with StatReloader <br>
                    Performing system checks... <br>
                    <br>
                    System check identified no issues (0 silenced). <br>
                    March 16, 2022 - 10:09:22 <br>
                    Django version 4.0.3, using settings 'pollday.settings' <br>
                    Starting development server at http://127.0.0.1:5000/ <br>
                    Quit the server with CONTROL-C.</span>
                </p class="qes">
            </div> 
            <li>
                Почему команда создания проекта или приложения "ничего не пишет"?
            </li>
            <div>
                <input type="button" value="&raquo;" onclick="toopen(this)">     
                <p class="qes">Комнада будет писать в случае скачивания пакетов установки,
                    при необходимости, так же в случае ошибки, либо нужна специальная команда. <br>
                    В другом случае при запуске проекта может не выводиться ни одно сообщение
                </p>
            </div>  
            <li>
                Как проверить результат работы команд создания проекта или приложения?
            </li>
            <div>
                <input type="button" value="&raquo;" onclick="toopen(this)">   
                <p class="qes">
                    По структуре папок(появятся необходимые для приложения или проекта папки) <br>
                    или по коду в файлах.
                </p>
            </div>  
            <li>
                В каком файле пишем код на питоне для создания html-страниц?
            </li>
            <div>
                <input type="button" value="&raquo;" onclick="toopen(this)">     
                <p class="qes">views.py

                </p>
            </div>  

            <h3>Специальный вопрос:</h3>
            <li>
                Как добавить стили в html?
            </li>
            <div> 
                <input type="button" value="&raquo;" onclick="toopen(this)">  
                <p class="qes">Для подключения стилей нужно в папке, где расположен views.py
                    добавить папку static в которой разместить файлы css. В коде html
                    добавить <span> &#123;% load static %&#125;</span>
                </p>
            </div>  
        </ol>
	</body>
</html>

pollday/polls/templates/polls/login.html
{% extends "base.html" %}
{% block title %}Вход{% endblock %}
{% block content %}
    <p>Введите имя пользователя и пароль:</p>
    <form method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Войти"></p>
    </form>
    <p> 
        <a href="{% url 'registration' %}">Регистрация</a>
    </p>
{% endblock %}

pollday/polls/templates/polls/logout.html
{% extends "base.html" %}
{% block title %}Выход{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        Пока {{ user.username }}!
        <p> Если захочешь 
            <a href="{% url 'login'%}">вернуться</a>
            , я буду только рад
        </p>
    {% else %}
    <p> Приглашаю <a href="{% url 'login'%}">войти</a> снова</p>
    {% endif %}
{% endblock %}

pollday/polls/templates/polls/registration.html
{% extends "base.html" %}
{% block title %}Регистрация{% endblock %}
{% block content %}
<p>Регистрация</p>
<form method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Войти">
</form>
{% endblock %}

pollday/polls/templates/polls/startpage.html
<!DOCTYPE html>
<html lang="ru">
	<head>
		<meta charset="utf-8">
		<title>
			Главная
		</title>
        <!-- {% load static %}

        
        <link rel="stylesheet" 
            type="text/css" 
            href="{% static 'style/style.css' %}">
        <link rel="stylesheet" 
            type="text/css" 
            href="{% static 'style/color.css' %}">
        <script
            src="{% static 'script/script.js' %}">
        </script> -->
	</head>
	<body>
        <h1>Выбери страницу</h1>
        <p>
            <a href="{% url 'index'%}">Вопросы</a>
        </p>
        <p>
            <a href="{% url 'dtnow'%}">Дата и время</a>
        </p>
        <p>
            <a href="{% url 'login' %}">Страница логина</a>
        </p>
	</body>
</html>

pollday/polls/templates/polls/succes_reg.html
{% extends "base.html" %}
{% block title %}Удача{% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        Привет {{ user.username }}!
    {% endif %}
    <p>Если захочешь <a href="{% url 'logout'%}">выйти</a>, я тебя не держу</p>
    {% if book_list %}
    <h1>Список книг</h1>
    <ul>
    {% for book in book_list %}
        <li> 
            {{book}}
        </li>
    {% endfor %}
    </ul>
    {%else%}
    <p>Нет книг &#9785; </p>
    {%endif%}
{% endblock %}

pollday/polls/templates/polls/userpage.html
{% extends "base.html" %}
{% block title %}Вход{% endblock %}
{% block content %}
{% if user.is_authenticated %}
<p>Привет {{ user.first_name }}!</p> 
<p> 
    Список доступных  <a href="{% url 'books'%}">книг</a>
</p>
<p>
    Если захочешь <a href="{% url 'logout'%}">выйти</a>, 
    я тебя не держу
</p>
{% endif %}
{% endblock %}